# Generated by Django 4.2.13 on 2024-05-26 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0002_products_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
