# Generated by Django 4.2.13 on 2024-05-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0004_alter_products_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
